on: [push]

name: AzureCLISampleForFile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup environment $RESOURCE_GROUP
      run: |
        chmod +x ./configuration.sh
        ./configuration.sh      
    

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.6.0
        inlineScript: |
          az deployment group create --resource-group $RESOURCE_GROUP --template-file $TEMPLATE_FILE --parameters azuredeploy.params.json
          az functionapp config appsettings set --name fappdeploykyspm --resource-group $RESOURCE_GROUP --settings "PATTOKEN=123456789"

